version: '3.1'

services:
  db:
    container_name: my-creative-collection-db
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
  pg-admin:
    container_name: my-creative-collection-pg-admin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - db