services:
  pg:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ~/containers/my-creative-collection-api-postgres-db:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped